### ISSUE TITLE
EnsembleVoteClassifier don't predict if classes represented as strings

### ISSUE THREAD

**Issue by pisarik** [rasbt/mlxtend#321] opened 2018-01-16 14:03 UTC
### Code to reproduce bug:

```python
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from mlxtend.classifier import EnsembleVoteClassifier

data = np.array([0, 1, 2, 3, 0, 1, 2, 3])[:, np.newaxis]
labels = ['a', 'b', 'c', 'd', 'a', 'b', 'c', 'd']

test = np.array([0, 1])[:, np.newaxis]

rf = RandomForestClassifier()
rf.fit(data, labels)
print(rf.predict(test))  # output: ['a', 'b']

clf = EnsembleVoteClassifier(clfs=[rf, rf], refit=False)
clf.fit(data, labels)
print(clf.predict(test))  # <-- error
```

### Stack trace:
```python
Traceback (most recent call last):  
  File "/_mlxtend_bug/reproduce.py", line 16, in <module>
    print(clf.predict(test))  
  File "/venv/py3/lib/python3.4/site-packages/mlxtend/classifier/ensemble_vote.py", line 197, in predict
    arr=predictions)  
  File "/venv/py3/lib/python3.4/site-packages/numpy/lib/shape_base.py", line 132, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))  
  File "/venv/py3/lib/python3.4/site-packages/mlxtend/classifier/ensemble_vote.py", line 195, in <lambda>
    weights=self.weights)),  
TypeError: Cannot cast array data from dtype('<U1') to dtype('int64') according to the rule 'safe'
```

### Problem code:
```python
else:  # 'hard' voting
            predictions = self._predict(X)

            maj = np.apply_along_axis(lambda x:
                                      np.argmax(np.bincount(x,
                                                weights=self.weights)),
                                      axis=1,
                                      arr=predictions)
```

### Probable solution:
It happens, because in this case aggregated classifiers return strings, and predictions comprise strings (or chars), **not** numbers. So we have to transform them back to **int** labels to use np.bincount:
```python
else:  # 'hard' voting
            predictions = self._predict(X)

            maj = np.apply_along_axis(lambda x:
                                      np.argmax(np.bincount(self.le_.transform(x),
                                                weights=self.weights)),
                                      axis=1,
                                      arr=predictions)
```

**Comment by rasbt** [comment] 2018-01-16 15:45
Thanks for the note! I wouldn't say this is a bug, but yeah, it currently doesn't handle string labels (I think the `Stacking`* classes currently also don't).

This should be easy to fix though by using e.g., the `LabelEncoder` from sklearn then working with those labels. It would be a good thing to modify the behavior of the `EnsembleVoteClassifier` and `Stacking` classes in future!

**Comment by rasbt** [comment] 2018-01-18 02:53
Sorry, I think I misread & misremembered. It seems that I added support for string labels a while back, but the issue is specific to `refit=False` and indeed a bug. I am going to fix that in #322

**Comment by rasbt** [comment] 2018-01-18 04:02
Should be fixed now in the master branch :)

**Closed** 2018-01-18 04:02 UTC
Labels: bug

**Comment by ben-ix** [comment] 2018-09-27 03:08
I am having a similar problem with the stacking classifier (using the latest version from pip). 

When calling
` self.meta_clf_.fit(all_model_predictions, reordered_labels)`

This fails for most meta_learners since all_model_predictions are strings.  I think the labels should be treated as integers so the meta classifier works as expected, as many (actually I think all) sklearn classifiers expect numeric input. This is my temporary workaround

```
class StackingCV(StackingCVClassifier):

    def fit(self, X, y):
        self.le = LabelEncoder()
        y = self.le.fit_transform(y)

        super().fit(X, y)

    def predict(self, X):
        predictions = super().predict(X)
        return self.le.inverse_transform(predictions)

```
