### ISSUE TITLE
Feature Request - Frequent Patterns 

### ISSUE THREAD

**Issue by Sanjoth** [rasbt/mlxtend#509] opened 2019-03-02 14:28 UTC
Suggestion to add **FP-Growth** and **Top-k Frequent itemsets** mining in frequent patterns library.

It would be great if mlxtend could have these 2 major algorithms which are also great for mining frequent patterns. It will be great if we can have all such tools in a single package.

Currently, the best FP-Growth implementation is in [Orange3](https://github.com/biolab/orange3-associate/blob/master/orangecontrib/associate/fpgrowth.py), but it doesn't have max_len which is a very big limitation when it comes to mining patterns in a large database.
As for top-k frequent itemsets mining, I didn't find any good library to use for production, it would be really great if these 2 can be added.

**Comment by rasbt** [comment] 2019-03-02 20:16
That's a good suggestion and I agree that this would be sth useful to have. There's an open issue about that -- currently "stale" though. I wouldn't have time to implement it myself at the moment but was hoping that someone else might be willing to help with a contribution here: #248.

**Comment by harenbergsd** [comment] 2019-05-30 22:09
I have an implementation of the FP-Growth algorithm (and the lesser known FPMax algorithm, which enumerates maximal itemsets), related to some research I was doing a while back.

I will look into into rewriting what I have in the style of this library and getting it added.

**Comment by rasbt** [comment] 2019-05-30 22:15
That would be amazing! The only real requirement/main consideration for the rewrite would be that it should have an interface similar to the current `apriori` implementation (http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/apriori/) such that the output will be compatible with the `association_rules` function (http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/)

**Comment by harenbergsd** [comment] 2019-06-07 23:38
@Sanjoth do you have a problem statement for top-k itemsets? Is it, find the k highest supported itemsets that are at least some specified size?

**Comment by harenbergsd** [comment] 2019-06-10 23:49
Now that fp-growth is added, I can also add [FPMax](http://users.encs.concordia.ca/~grahne/papers/hpdm03.pdf) if you want @rasbt?

**Comment by rasbt** [comment] 2019-06-11 02:39
I’ve actually never heard of FPMax — I am not an expert in this area — but I certainly would appreciate it. The more the merrier ;)

**Comment by Sanjoth** [comment] 2019-06-11 16:41
> @Sanjoth do you have a problem statement for top-k itemsets? Is it, find the k highest supported itemsets that are at least some specified size?

Hi @harenbergsd, apologies for the delayed response, the problem statement is to find the top k (length) frequent itemsets with a minimum support threshold. This will be helpful for bundled products, but I'm still hazy on the implementation.

**Comment by harenbergsd** [comment] 2019-06-12 01:02
@Sanjoth Ok great, thanks. 

I am going to add FPMax, which finds _maximal_ itemsets (a subset of closed itemsets). It would be easy to report the top-k for this; e.g., a straightforward solution is just sort the output and return top-k supported itemsets. However, a better implementation would be to create some kind of priority queue and cull the search space based on the current top-k.

Based on [this paper](http://users.encs.concordia.ca/~grahne/papers/fimi03.pdf), I can get a closed itemset mining algorithm with some tweaks to FPMax (which itself is a tweak to FP-Growth), so I will implement that as well.

Once I finish these we will have support for maximal and closed itemsets and optionally top-k for both.

**Comment by rasbt** [comment] 2019-06-12 08:08
Like you suggest, @harenbergsd regarding the top-k, this could also be added as an documentation example or meta algorithm that operates on top of the apriori/fp-growth/fp-max outputs (and later, it may be implemented more efficiently in a one-go kind of way.

**Comment by rasbt** [comment] 2019-06-23 17:07
> top k closed frequent itemsets

As far as I know, closed itemsets are slightly different from maximal itemsets by definition (I think there's also an FPClosed variant of FP-Growth). However, I guess the FPMax getting the top-k itemsets by support should probably already do the job well. I would say let's close this for now, but if there are any questions, we can reopen it -- or add a separate issue on FPClosed at some point.

**Closed by rasbt** 2019-06-23 17:07 UTC
Labels: help wanted, new feature

**Comment by morgenthd** [comment] 2020-03-25 16:08
I've been using FPMax with random subsets of large list encoded (TransactionEncoder) and placed in a DataFrame. FPMax sometimes seems to enter an infinite loop (or at least it exceeds my patience). If I restart, so that I'm using a different random subset, FPMax will finish rather quickly. Is there some conditioning that I could do to my inputs to prevent the seemingly infinite looping?

**Comment by harenbergsd** [comment] 2020-03-27 03:00
@morgenthd If you try changing the support, max length, etc. does that cause it to go faster? Could it just be that some random datasets you generate happen to cause a large number of frequent patterns, therefore taking a long time to finish? If you paste your code and give me two random seeds that cause fpmax to go quickly and slow and I will look at it.

**Comment by rasbt** [comment] 2020-03-27 04:24
In addition to what @harenbergsd suggested, could you let us know which version you are using? I remember there was a small update in 0.17.1.

Another thing you can try, as a means to investigate whether it gets stuck: could you set `verbose=1` and see whether it makes progress?

**Comment by morgenthd** [comment] 2020-03-27 15:05
Thank you both for your swift replies.

   - I have experimented extensively with changing the support, but not the
   maxlength. My initial dataset has ~125K baskets containing frequent sets
   that range from support in 33K baskets to support in only 2 baskets. I am
   trying to make a list of all the frequent sets and a list of baskets that
   contain each frequent set.
   My approach has been as follows:
      - Get a random sample of 10% of the baskets (12.5K), and find
      frequent sets with support of more than 1.25K (1%).   Once the frequent
      sets are found, I pass through all 125K of the original baskets either
      associating them with a frequent set or collecting them as
residuals.  This
      successfulliy finds frequent sets found in  33K, 30K, 20k, ....baskets.
      - This process is repeated on the residual iteratively -- random
      sample, compute frequent sets of the random sample, pass through all the
      residuals trying to associate baskets with frequent sets, and repeat wth
      the residual

The problem is that on the third iteration (or fourth, which has happened
as I've change the sample size and the support size used at each itration)
the computation goes away and doesn't return. After submitting my question
to you I've observed that my memory use explodes (well above 32GB RAM) and
I start using a lot of virtual memory. This likely explains the very long
compute times.

My current hypothesis is that by the third or fourth iteration I may be
looking for a support level that doesn't exist in the data, either too high
or too low. But of this I'm not convinced.


   - Regarding the random seeds: I captured seeds (at the very start) so
   that following a successful run I could begin with the same seed. I was
   surprised when this didn't result in another successful run. I'm using
   numpy.random's seed, with sklearn's test_train_split to make the random
   samples. I think sklearn uses numpy.random, so I don't understand why this
   didn't work for me. But the short answer is that I don't have successful
   seeds.
   - I'm using version 0.17.2

If you have any thoughts based on the above I'm curious to hear them. But
at this point I don't wish you to spend too much time with this. I've
restructured and found a successful approach (Compute frequent sets for
each batch of 10K baskets, merge similar/identical frequent sets form these
~12 batches, and finally make a single pass through the baskets to
associate them with one of the surviving frequent sets. There is a bit of
danger in merging, but it hasn't been an issue.)  This approach works
swiftly and to completion.

Thanks again for your time and attention. And stay safe!

**Comment by harenbergsd** [comment] 2020-03-28 04:38
I am not sure I fully understand what you are doing, but if you are decreasing the support, it's possible you are just hitting a combinatorial explosion, which would not be too surprising.

I'd be interested looking at your test to see if fpmax performance could be improved, so if it's easy then you could upload the code you are running.

Otherwise, I am glad you found a process that works for you.
